version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: tempchat-db
    environment:
      POSTGRES_DB: tempchat
      POSTGRES_USER: tempchat
      POSTGRES_PASSWORD: tempchat_pass
    ports:
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
